name: minimal-animatediff
channels:
  - pytorch
  - xformers
dependencies:
  - cudatoolkit=11.3
  - pip
  - python=3.10
  - pytorch==1.12.1
  - torchvision==0.13.1
  - xformers
  - pip:
    - diffusers[torch]==0.11.1
    - einops
    - gdown
    - huggingface_hub
    - imageio==2.27.0
    - pylint
    - safetensors
    - transformers==4.25.1
    - triton
