name: test
on:
  workflow_dispatch:
  pull_request:
    branches: ['*', '!latest']
  push:
    branches: [latest, main]
jobs:
  lib:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          submodules: true

      - name: Check lint
        shell: fish {0}
        run: |
          conda activate minimal-animatediff
          python3 -m pylint modules scripts

      - name: Run tests
        shell: fish {0}
        run: |
          conda activate minimal-animatediff
          python3 -m pytest -v -s --durations=0
