name: test
on:
  workflow_dispatch:
  pull_request:
    branches: ['*', '!latest']
  push:
    branches: [latest, main]
jobs:
  lib:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          submodules: true

      - name: Run tests
        shell: fish {0}
        run: |
          conda activate minimal-animatediff
          make test

      - name: Check diff
        run: git diff --exit-code HEAD
